default_stages: [commit]
repos:
  # standard built in pre-commit hooks
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace # Removes trailing whitespaces
    -   id: end-of-file-fixer # Makes sure files end in a newline and only a newline
    -   id: check-yaml # Loads all yaml files to verify syntax
    -   id: check-added-large-files # Prevents giant files from being committed (default=500kB)
    -   id: debug-statements # Removes debug statements which should never be in production

  # Python code formatter
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.8.0
    hooks:
      # Run the linter.
    -   id: ruff
        types_or: [python, pyi, jupyter]
        args: [--fix]
      # # Run the formatter.
      # - id: ruff-format
      #   types_or: [ python, pyi, jupyter ]

# Sync pre-commit hooks to latest versions of black and flake8
-   repo: https://github.com/mxr/sync-pre-commit-deps
    rev: v0.0.1
    hooks:
    -   id: sync-pre-commit-deps

  # Python code formatter
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: ["--line-length", "120"]
        additional_dependencies:
        -   "click==8.1.3" # Required in order for black to run
    -   id: black-jupyter
        args: ["--line-length", "120"]

  # Run black on python code blocks in documentation files
-   repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    -   id: blacken-docs
        additional_dependencies:
        -   "black==22.3.0"

  # Sort your imports automatically
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

  # autoflake removes unused import statements, config in args below
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--ignore-init-module-imports']


  # Toolkit for checking your code base against coding style (PEP8), programming errors and check cyclomatic complexity
-   repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    -   id: flake8
        additional_dependencies:
        -   "flake8-bandit==2.1.2"
        -   "flake8-bugbear==22.1.11"
        -   "flake8-docstrings==1.6.0"
        -   "bandit==1.7.2" # Required in order for flake8 to run

  # To enforce type hinting
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.0
    hooks:
    -   id: mypy
        args: ["--ignore-missing-imports", "--disable-error-code", "no-any-unimported"]
        exclude: ^((tests)|(docs)|(notebooks)|(^.*notebook.py))
        additional_dependencies:
        -   "types-PyYAML"

  # Notebook remove results
-   repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
    -   id: nbstripout

  # SQL linter that supports many dialects
-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.5
    hooks:
    -   id: sqlfluff-lint

  # A systems hook that just runs php -l against stage files that have the .php extension
-   repo: https://github.com/digitalpulp/pre-commit-php.git
    rev: 1.4.0
    hooks:
    -   id: php-lint-all

  # validate Markdown / RST files
-   repo: https://github.com/Lucas-C/pre-commit-hooks-markup
    rev: v1.0.1
    hooks:
    -   id: rst-linter

  # Syntax update for newer Python versions
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.19.0
    hooks:
    -   id: pyupgrade
